Document: sakis3g
Title: Debian sakis3g Manual
Author: <insert document author here>
Abstract: This manual describes what sakis3g is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sakis3g/sakis3g.sgml.gz

Format: postscript
Files: /usr/share/doc/sakis3g/sakis3g.ps.gz

Format: text
Files: /usr/share/doc/sakis3g/sakis3g.text.gz

Format: HTML
Index: /usr/share/doc/sakis3g/html/index.html
Files: /usr/share/doc/sakis3g/html/*.html
